/// Dimension table of information for each shooting session
table dim_session
	lineageTag: 05e65518-a919-4c75-a671-443a92a8bdd7

	column date
		dataType: dateTime
		formatString: Short Date
		lineageTag: eebb2a20-d29f-43b1-b548-97f82658f561
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column notes
		dataType: string
		lineageTag: 65ae86d9-dbbd-4964-837d-56f9145c2591
		summarizeBy: none
		sourceColumn: notes

		annotation SummarizationSetBy = Automatic

	column major_adjustment
		dataType: string
		lineageTag: ff1e3ea4-2f1b-4a79-8f9e-b218bb3cc1f3
		summarizeBy: none
		sourceColumn: major_adjustment

		annotation SummarizationSetBy = Automatic

	column session_id
		dataType: int64
		formatString: 0
		lineageTag: bb67f8b1-e1c2-4820-abc1-ee577d7545c0
		summarizeBy: none
		sourceColumn: session_id

		annotation SummarizationSetBy = Automatic

	column session_end_count
		dataType: int64
		formatString: 0
		lineageTag: 97e25b38-7cdb-4cad-ac1b-91a3820c7fdc
		summarizeBy: sum
		sourceColumn: session_end_count

		annotation SummarizationSetBy = Automatic

	column session_shot_count
		dataType: int64
		formatString: 0
		lineageTag: 047b9acd-efe7-4825-bd91-2ea511537067
		summarizeBy: sum
		sourceColumn: session_shot_count

		annotation SummarizationSetBy = Automatic

	column days_since_previous_session
		dataType: int64
		formatString: 0
		lineageTag: 5a6c728e-9aea-4535-b155-fb2c0106a1e2
		summarizeBy: sum
		sourceColumn: days_since_previous_session

		annotation SummarizationSetBy = Automatic

	column days_since_previous_session_buckets
		dataType: string
		lineageTag: 51470912-358b-4310-b9de-1056cec9d4fe
		summarizeBy: none
		sourceColumn: days_since_previous_session_buckets

		annotation SummarizationSetBy = Automatic

	column shot_count_per_end
		dataType: decimal
		formatString: 0.0
		lineageTag: 81519720-0f0c-40aa-acf7-c2088aef9b43
		summarizeBy: sum
		sourceColumn: shot_count_per_end

		annotation SummarizationSetBy = Automatic

	column session_shot_count_buckets
		dataType: string
		lineageTag: 4ad71c61-0bac-425f-9394-815f5da0b692
		summarizeBy: none
		sourceColumn: session_shot_count_buckets
		sortByColumn: session_shot_count_rounded

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column shot_count_per_end_buckets
		dataType: string
		lineageTag: e4322097-29bf-47e4-b463-c815fdc92225
		summarizeBy: none
		sourceColumn: shot_count_per_end_buckets
		sortByColumn: shot_count_per_end_rounded

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column session_shot_count_rounded
		dataType: int64
		formatString: 0
		lineageTag: 99adde56-7a1e-4b05-8a95-2593dcf9a61b
		summarizeBy: sum
		sourceColumn: session_shot_count_rounded

		annotation SummarizationSetBy = Automatic

	column shot_count_per_end_rounded
		dataType: decimal
		formatString: 0.0
		lineageTag: 72fb94d0-a3bb-4d55-9663-6e53f7fc9a4b
		summarizeBy: sum
		sourceColumn: shot_count_per_end_rounded

		annotation SummarizationSetBy = Automatic

	column session_score_average
		dataType: decimal
		formatString: 0.0
		lineageTag: f47a9d32-4478-4e88-aa04-a72cc1a46fab
		summarizeBy: sum
		sourceColumn: session_score_average

		annotation SummarizationSetBy = Automatic

	column latest_major_adjustment
		dataType: string
		lineageTag: a4cbea61-a932-4059-92f3-c6af39c32e4f
		summarizeBy: none
		sourceColumn: latest_major_adjustment

		annotation SummarizationSetBy = Automatic

	partition dim_session = m
		mode: import
		queryGroup: 'Table Queries'
		source =
				let
				    Source = raw_shot_data,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"date", "notes", "major_adjustment", "session_id"}),
				    #"Merged Queries" = Table.NestedJoin(#"Removed Other Columns", {"session_id"}, score_session_agg, {"session_id"}, "session_counts", JoinKind.LeftOuter),
				    #"Expanded session_counts" = Table.ExpandTableColumn(#"Merged Queries", "session_counts", {"session_end_count", "session_shot_count", "session_score_average"}),
				    #"Added Custom" = Table.AddColumn( #"Expanded session_counts", "days_since_previous_session", each if [session_id] > 1 then Duration.Days( [date] - (#"Expanded session_counts"[date]{[session_id] - 2}) ) else null, Int64.Type ),
				    #"Added Conditional Column" = Table.AddColumn(#"Added Custom", "days_since_previous_session_buckets", each if [days_since_previous_session] = null then null else if [days_since_previous_session] > 7 then "8+" else Number.ToText( [days_since_previous_session], "#" ), type text),
				    #"Inserted Division" = Table.AddColumn(#"Added Conditional Column", "shot_count_per_end", each Number.Round( [session_shot_count] / [session_end_count], 2 ), Currency.Type),
				    #"Inserted Round Down" = Table.AddColumn(#"Inserted Division", "session_shot_count_rounded", each Number.RoundDown([session_shot_count], -1), Int64.Type),
				    #"Added Custom1" = Table.AddColumn(#"Inserted Round Down", "session_shot_count_buckets", each Number.ToText( [session_shot_count_rounded] ) & " - " & Number.ToText( [session_shot_count_rounded] + 9 ), type text),
				    #"Inserted Round Down1" = Table.AddColumn(#"Added Custom1", "shot_count_per_end_rounded", each Number.RoundDown([shot_count_per_end] * 2) / 2, Currency.Type),
				    #"Added Custom2" = Table.AddColumn(#"Inserted Round Down1", "shot_count_per_end_buckets", each Number.ToText( [shot_count_per_end_rounded] ) & " - " & Number.ToText( [shot_count_per_end_rounded] + .5 ), type text),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Added Custom2", "major_adjustment", "latest_major_adjustment"),
				    #"Filled Down" = Table.FillDown(#"Duplicated Column",{"latest_major_adjustment"})
				in
				    #"Filled Down"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

