/// Fact table of rolling scores for each end based on a 30 shot round
table fact_round_score_30
	lineageTag: 135b9dfd-c8dd-430b-89cd-5e3fec2beb01

	column end_id
		dataType: int64
		formatString: 0
		lineageTag: 506c853d-3bda-419f-9190-90fe8dd4a50d
		summarizeBy: none
		sourceColumn: end_id

		annotation SummarizationSetBy = Automatic

	column starting_end
		dataType: int64
		formatString: 0
		lineageTag: c236b2aa-6261-4cbd-bb41-5f35c9d1a196
		summarizeBy: sum
		sourceColumn: starting_end

		annotation SummarizationSetBy = Automatic

	column round_score
		dataType: int64
		formatString: 0
		lineageTag: 2ab281ab-bf1f-473d-9519-4b0f42133337
		summarizeBy: sum
		sourceColumn: round_score

		annotation SummarizationSetBy = Automatic

	partition fact_round_score_30 = m
		mode: import
		queryGroup: 'Table Queries'
		source =
				let
				    // Variable for total shots in a round
				    round_total_shot_count = 30,
				    Source = cumulative_end_score,
				    #"Merged Queries" = Table.NestedJoin(Source, {"session_id"}, Source, {"session_id"}, "self_join", JoinKind.LeftOuter),
				    #"Expanded self_join" = Table.ExpandTableColumn(#"Merged Queries", "self_join", {"end", "shot_count", "score", "cumulative_shot_count", "cumulative_score"}, {"starting_end", "starting_shot_count", "starting_score", "starting_cumulative_shot_count", "starting_cumulative_score"}),
				    #"Added Custom" = Table.AddColumn(#"Expanded self_join", "round_shot_count", each [cumulative_shot_count] - [starting_cumulative_shot_count] + [starting_shot_count], Int64.Type),
				    #"Filtered Rows1" = Table.SelectRows(#"Added Custom", each [round_shot_count] >= round_total_shot_count),
				    #"Sorted Rows" = Table.Sort(#"Filtered Rows1",{{"session_id", Order.Ascending}, {"end", Order.Ascending}, {"starting_end", Order.Descending}}),
				    #"Added Index" = Table.AddIndexColumn(#"Sorted Rows", "index", 1, 1, Int64.Type),
				    #"Removed Duplicates" = Table.Distinct(#"Added Index", {"session_id", "end"}),
				    #"Added Custom1" = Table.AddColumn(#"Removed Duplicates", "round_score", each Number.Round( ([cumulative_score] - [starting_cumulative_score] + [starting_score]) / [round_shot_count] * round_total_shot_count ), Int64.Type),
				    #"Removed Other Columns" = Table.SelectColumns(#"Added Custom1",{"end_id", "starting_end", "round_score"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

