/// Fact table of scores for each shot taken
table fact_shot_score
	lineageTag: e6891884-0821-44e6-a257-b96b37aa6cd8

	column score
		dataType: int64
		formatString: 0
		lineageTag: f448e191-474b-4191-9612-c9223dab0463
		summarizeBy: none
		sourceColumn: score

		annotation SummarizationSetBy = Automatic

	column score_end_average
		dataType: decimal
		formatString: 0.00
		lineageTag: b31eee47-36ee-43bb-ac88-9df71fe2f4dc
		summarizeBy: sum
		sourceColumn: score_end_average

		annotation SummarizationSetBy = Automatic

	column session_shot_id
		dataType: int64
		formatString: 0
		lineageTag: ec380635-65b5-4740-8f33-e727998b4e62
		summarizeBy: sum
		sourceColumn: session_shot_id

		annotation SummarizationSetBy = Automatic

	column shot_id
		dataType: int64
		formatString: 0
		lineageTag: ded94982-77ac-4e3a-a6a0-d061a6ae4de7
		summarizeBy: sum
		sourceColumn: shot_id

		annotation SummarizationSetBy = Automatic

	column session_id
		dataType: int64
		formatString: 0
		lineageTag: e42132a5-77ed-433b-bd09-4841aee8c064
		summarizeBy: none
		sourceColumn: session_id

		annotation SummarizationSetBy = Automatic

	column end
		dataType: int64
		formatString: 0
		lineageTag: b89daec6-a380-4466-9a91-a0924e9a1346
		summarizeBy: sum
		sourceColumn: end

		annotation SummarizationSetBy = Automatic

	partition fact_shot_score = m
		mode: import
		queryGroup: 'Table Queries'
		source =
				let
				    Source = Table.NestedJoin(score_shot_agg, {"session_id", "end"}, score_end_agg, {"session_id", "end"}, "end_counts", JoinKind.LeftOuter),
				    #"Expanded end_counts" = Table.ExpandTableColumn(Source, "end_counts", {"score_end_average"})
				in
				    #"Expanded end_counts"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

