table select_scoring_pace_features
	lineageTag: 25ef34ae-41c3-4a78-b365-3aae09a37ecb

	column feature_id
		dataType: int64
		formatString: 0
		lineageTag: 5d55a518-896f-463b-81e7-115ad05e1db3
		summarizeBy: sum
		sourceColumn: feature_id

		annotation SummarizationSetBy = Automatic

	column feature_name
		dataType: string
		lineageTag: 2199478a-b7e1-42da-b2ac-da4afab0e376
		summarizeBy: none
		sourceColumn: feature_name
		sortByColumn: feature_id

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition select_scoring_pace_features = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUXIuzS3NSSzJLEtVCE7OL8rMS1cISExOVYrViVYyAsoHpBYpBGfkl2DKGgNlgxNzC3KAOjOrUhU0lBWCU4uLM/PzijXBCkyACsITi3IVQgsUEvNSFFxSk3My84CaYwE=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [feature_id = _t, feature_name = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"feature_id", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

