table select_data_table_colors
	lineageTag: 1012ce1e-abae-4db7-8bd3-30ff6782116b

	column color_scheme
		dataType: string
		lineageTag: 93b12c6b-6fe4-4733-b0d6-9a703747d6f9
		summarizeBy: none
		sourceColumn: color_scheme
		sortByColumn: scheme_id

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column scheme_id
		dataType: int64
		formatString: 0
		lineageTag: 13028a08-c8c2-4ef7-9712-e090e4950719
		summarizeBy: sum
		sourceColumn: scheme_id

		annotation SummarizationSetBy = Automatic

	column color_4_0
		dataType: string
		lineageTag: 828e7468-bbb0-49df-94a3-10526da0371c
		summarizeBy: none
		sourceColumn: color_4_0

		annotation SummarizationSetBy = Automatic

	column color_8
		dataType: string
		lineageTag: ca8c0abd-a9f9-4ed6-833f-35ce93f5e3f5
		summarizeBy: none
		sourceColumn: color_8

		annotation SummarizationSetBy = Automatic

	column color_7
		dataType: string
		lineageTag: 510eb9fa-2d90-4f99-8366-7b73ca0dc50b
		summarizeBy: none
		sourceColumn: color_7

		annotation SummarizationSetBy = Automatic

	column color_6
		dataType: string
		lineageTag: 2fc0fe4b-6168-4088-84a6-e9528acb7d75
		summarizeBy: none
		sourceColumn: color_6

		annotation SummarizationSetBy = Automatic

	column color_5
		dataType: string
		lineageTag: fbfa38fe-151c-49ed-85cb-7b4e6a538290
		summarizeBy: none
		sourceColumn: color_5

		annotation SummarizationSetBy = Automatic

	column color_10
		dataType: string
		lineageTag: f8a71b3f-b132-4cba-991e-cd495cb7336b
		summarizeBy: none
		sourceColumn: color_10

		annotation SummarizationSetBy = Automatic

	column color_9
		dataType: string
		lineageTag: 1e75a858-ea76-4b91-864a-231ad057da14
		summarizeBy: none
		sourceColumn: color_9

		annotation SummarizationSetBy = Automatic

	partition select_data_table_colors = m
		mode: import
		queryGroup: 'Table Queries'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("bY/BCsIwDIZfRep1B9vY0h6bNXkBvY0dPBQZTJGhPr9bDp2dNhQ+Evjyp+vU+TJd83PHr3FUjdLz3xMSghADgwfpeXDgpKe980KAnknIB2z5sFCApVTfFPNpuD3GPM+MeJjYxg0lS5ZqciZawpq+3Gl459l+L8ElpGkdxlRHQ50MW5HLkxNc5Mj1WZFMMGEjL9mPtfSffqVV/7Oo7z8=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [color_scheme = _t, scheme_id = _t, color_10 = _t, color_9 = _t, color_8 = _t, color_7 = _t, color_6 = _t, color_5 = _t, color_4_0 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"scheme_id", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

